### ISSUE TITLE
remove proposal_name that require proposer to fill in as PK

### ISSUE THREAD

**Issue by libhasheos** [boscore/referendum#33]
Currently there are two parameters in propose page:
**proposal name** and **title** which is confusing for developers.

Basically `proposal_name` is the PK for `proposal_row`  table
https://github.com/boscore/referendum/blob/84e28b1daa7a91f37fc8f924642fe46f737da493/contracts/eosio.forum/include/forum.hpp#L87-L100

It's necessary to remove the burden for develop to key in this 12 character primary key and allow either auto-incremental PK or random identifier to be generated to identify a particular proposal.

**https://boswps.io**
![image](https://user-images.githubusercontent.com/45421310/58322650-2be08d80-7e54-11e9-86cb-c985c57db4b0.png)

**Comment by DenisCarriere** [comment]
Using auto increment makes it very challenging for others to find/approve a particular escrow.

This is the same as submitting an MSIG proposal, adding a 12 character unique ID is very easy for devs/propopers
