### ISSUE TITLE
can't submit proposal

### ISSUE THREAD

**Issue by igorls** [boscore/referendum#36]
When trying to submit a proposal with or without markdown content via https://www.boswps.io and with Scatter Desktop (login works), an error is given

Create ERROR[object Object]

Nothing else is logged on the browser console and Scatter is not called

**Comment by icelanDesert** [comment]
Maybe because the signature request is rejected in scatter,
we will add better error log soon

**Comment by igorls** [comment]
Closing the issue since the error is related to a regression on scatter 11, already reported to them. Submission is working fine on v10
