### ISSUE TITLE
"Incentives" and "Receipt account" do not recorded on the blockchain when create proposal use boswps.io

### ISSUE THREAD

**Issue by whoami-chens** [boscore/referendum#38]
"Incentives" and "Receipt account" do not recorded on the blockchain when create proposal use boswps.io

In page of [create proposal](https://boswps.io/#/create_proposal),there has "Incentives" and "Receipt account" field.
![image](https://user-images.githubusercontent.com/45056105/58367745-239c5700-7f15-11e9-8a85-050fbc0fcaf5.png)

But in the [contract](https://github.com/boscore/referendum/blob/master/contracts/eosio.forum/src/forum.cpp#L11), no usage of them .
![image](https://user-images.githubusercontent.com/45056105/58367805-1af85080-7f16-11e9-9dd8-2dc77d40a3e1.png)

**Comment by DenisCarriere** [comment]
This metadata should be stored in `proposal_json`

Propose a metadata WPS schema and the community can adapt it.

No changes required in `eosio.forum`
